# This is a basic workflow to help you get started with Actions

name: Scrape-and-send-msg

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 8 am every day
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrape"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@v2
        with:
            python-version: '3.9'
            cache: 'pipenv'
      - run: pipenv install --python `which python`


      #name: Install sqlite_utils
        #run: pip install sqlite_utils

      # Step: install requirments on the cloud computer that has
      # cloned your repo.
      - name: Install libraries
        run: |
          pip install requests
          pip install sqlite_utils
          pip install slackclient
          pip install bs4






        #run: |
          #echo python -m pip install requests
          #echo python -m pip install sqlite_utils

      # Step: run the python script
      - name: Run script to scrape data
        run: sh ./app.sh
