# This is a basic workflow to help you get started with Actions

name: send_slack_msg


# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 8 am every day
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrape"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@v2
        with:
            python-version: '3.9'
            cache: 'pipenv'
      - run: pipenv install --python `which python`


      #name: Install sqlite_utils
        #run: pip install sqlite_utils

      # Step: install requirments on the cloud computer that has
      # cloned your repo.
      - name: Install libraries
        run: |-
          pip install requests
          pip install sqlite_utils
          pip install slackclient
          pip install bs4
          pip install python-dotenv


        #run: |
          #echo python -m pip install requests
          #echo python -m pip install sqlite_utils

      # Step: run the python script
      - name: Run script to scrape data
        env: # Or as an environment variable
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: sh ./app.sh
      - name: Commit and push csv and db
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add food_inspections.csv food_inspections.db
          timestamp=$(date -u)
          git commit -m "Latest csv update: ${timestamp}" || exit 0
          git push
